In [13]:
import numpy as np
import math

a = [1, 2, 3, 4, 5]
b = np.array([np.array(a)])

b

array([[1, 2, 3, 4, 5]])

In [19]:
array_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_3x3)
array_3x3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [20]:
# The shape of a Numpy-array tells us, in essence, how many ROWS (FIRST) and COLUMNS (SECOND) a given array has.
# Note that if we make an array that has lists that don't match shapes, for example a list containing 3 other
# lists that have lengths 3, 3, and 2, then we will simply get an array with shape (3,), i.e. a list of length
# 3. This is because Numpy then treats it as an object, rather than a matrix.
# However if we then actually have an array of 3 lists, all of which have length 3, then the shape becomes (3, 3)
# Let's now try to create a matrix in numpy that looks like the following:

#     [[1, 2, 3],
#      [4, 5, 6],
#      [7, 8, 9]]

list1 = np.array([1, 2, 3])
list2 = np.array([4, 5, 6])
list3 = np.array([7, 8, 9])

res = np.array([list1, list2, list3])
print(res)
res.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [34]:
# Now let's test reshaping this array. I will comment what I want the result to be, and then try to make it
# I want the 3x3 matrix to become a single row, i.e. 1D array. I will try to use reshape to do this
new_array_1d = res.reshape(1,-1)
print(new_array_1d)

# Turns out, in order to make 2D into 1D, we gotta use flatten
flattened = new_array_1d.flatten()
print(flattened)

# Now I'm gonna create a 4x4 matrix
new_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15 ,16]])
print(new_4x4)

# Now I want another matrix that has 2 rows and 8 columns
new_2x8 = new_4x4.reshape(2, 8)
print(new_2x8)

# Now let's take the above matrix, and instead make 8 rows with 2 columns. I want to have [[1,2], [3,4], [5,6], ..]
new_8x2 = new_2x8.reshape(8, 2)
print(new_8x2)

# Now just for fun let me have 1 column with 16 rows
many_16_rows = new_8x2.reshape(16, -1)
print(many_16_rows)

[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [35]:
a = np.array(range(6)).reshape(2,3)
print('      a = \n', a)
b = np.array([1]*15).reshape(3,5)
print('      b = \n', b)
v = np.random.uniform(0,1,5)  # v looks like a column vector, since dims = (5,)
print('v.shape = ', v.shape)
print('    v = \n', v)  # But numpy prints it as a row vector.  It can be either, depending upon the context.
u = np.random.uniform(10,20,5)
print('   u * v = \n ', np.dot(u,v))
print('b * v = \n', np.dot(b,v))  # Here, numpy treats v as a column vector
print(' v * bT = \n', np.dot(v,np.transpose(b)))  # Here, nump treats v as a row vector.

      a = 
 [[0 1 2]
 [3 4 5]]
      b = 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
v.shape =  (5,)
    v = 
 [0.06980912 0.16253915 0.88778721 0.1657454  0.19689067]
   u * v = 
  18.67881823408044
b * v = 
 [1.48277156 1.48277156 1.48277156]
 v * bT = 
 [1.48277156 1.48277156 1.48277156]


In numpy, np.matmul and np.dot are very similar, but they handle "broadcasting" (i.e. duplicating sections
in order to make array-combination operators work) differently.  np.einsum is more complex, and more 
low-level, but it's a superset of matmul, dot and many other numpy array operations.

The first argument to einsum is the subscript string, for example 'ij,j->i' in the code below.  
This shows how the one or two arrays (i.e. operands) on the left of the arrow 
will be converted into the array on the right 
of the arrow.  When the same letter appears in both operands (e.g. 'j' in 'ij,j->i'), this means that
corresponding elements in the two vectors (columns in operand 1, rows in operand 2) will be multiplied
together.  Then, the ABSENCE of that same letter on the right-hand-side of the subscript string indicates
that those products will be summed.  So together, the repeat letter plus its absence on the right is 
einsum code for a dot product.

In [2]:
print(np.matmul(b,v))
print(np.dot(b,v))  # np.dot does matrix multiplications, not just dot products.
print(np.einsum('ij,j->i',b,v))  # Einsum does this and MUCH more
print('  einsum pairwise multiply = ',np.einsum('i,i->i',u,v))
print('   einsum dot product =', np.einsum('i,i',u,v))  # simple dot product with einsum
print('   a * b = \n', np.dot(a,b))

[2.88813492 2.88813492 2.88813492]
[2.88813492 2.88813492 2.88813492]
[2.88813492 2.88813492 2.88813492]
  einsum pairwise multiply =  [11.21656195 12.65856963  1.45309149 14.10061477  9.47420993]
   einsum dot product = 48.90304777724347
   a * b = 
 [[ 3  3  3  3  3]
 [12 12 12 12 12]]


Einsum can be used to sum along one or more axes of an array.  In the notation 'ijk->ij', the absence of
the k on the right-hand-side of the arrow means that that dimension shall be summed over.

In [40]:
print(np.einsum('ij->i',b))  # Sum the rows, preserving number of rows (i) but reducing # dimensions by 1.
print(np.einsum('ij->j',b))  # Sum the columns, preserving number of columns (j) but reducing # dimensions by 1.
m = np.array(range(24)).reshape(2,3,4)  # m = a 3-d array
print(f"m: {m}")
test_ein_1 = np.einsum('ijk->ij', m)
print(f"Test 1: {test_ein_1}")
# print('\n', np.einsum('ijk->ik',m)) # sum over 2nd dim, retaining 1st and 3rd dimensions
# print('\n', np.einsum('ijk->k',m)) # sum over 1st and 2nd dimensions, leaving a vector of size k.
# print('\n', np.einsum('ijk->',m)) # sum the entire array
# print('\n', np.einsum('ijk',m)) # This just returns the array, unaltered.

[5 5 5]
[3 3 3 3 3]
m: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Test 1: [[ 6 22 38]
 [54 70 86]]


Einsum can be used to pick out a diagonal of a matrix (as with np.diag) or to SUM the elements of a diagonal
(as with np.trace).

In [4]:
z = np.array(range(25)).reshape(5,5)
print('z = \n', z, '\n')
print('Diagonal(z) = ', np.diag(z))  # Pick out the main diagonal of this square matrix
print('Trace(z) = ', np.trace(z))    # Sum the main diagonal
print('Diagonal and Trace using Einsum: ')
print(np.einsum('ii->i',z))  # Return the diagonal
print(np.einsum('ii->',z))  # sum the diagonal == trace

z = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Diagonal(z) =  [ 0  6 12 18 24]
Trace(z) =  60
Diagonal and Trace using Einsum: 
[ 0  6 12 18 24]
60


You can use np.diag to CONSTRUCT a diagonal matrix also.  Just send it a vector.

In [5]:
print(np.diag([1,2,3,4]))
print(np.diag(np.diag(z)))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 0  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 24]]


Transposing a matrix using einsum instead of np.transpose

In [6]:
print(np.einsum('ij->ji',z))

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


The outer product of two vectors, as with np.outer, can also be done with einsum

In [7]:
u = np.array(range(5))
v = u * 100
print('u = ', u, ' v = ', v)
print('Using outer: \n', np.outer(u,v))
print('Using Einsum: \n', np.einsum('i,j->ij',u,v))

u =  [0 1 2 3 4]  v =  [  0 100 200 300 400]
Using outer: 
 [[   0    0    0    0    0]
 [   0  100  200  300  400]
 [   0  200  400  600  800]
 [   0  300  600  900 1200]
 [   0  400  800 1200 1600]]
Using Einsum: 
 [[   0    0    0    0    0]
 [   0  100  200  300  400]
 [   0  200  400  600  800]
 [   0  300  600  900 1200]
 [   0  400  800 1200 1600]]


Multiplying corresponding elements in two arrays and returning the product array

In [8]:
print('m = \n', m)
print('m * m = \n', m*m)
print('With einsum: \n', np.einsum('ijk,ijk->ijk',m,m))

m = 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
m * m = 
 [[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[144 169 196 225]
  [256 289 324 361]
  [400 441 484 529]]]
With einsum: 
 [[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[144 169 196 225]
  [256 289 324 361]
  [400 441 484 529]]]


Multiplying all elements along one axis of an array with corresponding elements in a vector:

In [9]:
print('shape of m = ',m.shape)
q = np.array([-1,100])
print('Multiply each sub-matrix by either -1 or 100: \n', np.einsum('ijk,i->ijk',m,q))
c = np.array([1,100,10000])
print('Multiply rows of each sub-matrix by either 1, 100 or 10000: \n', np.einsum('ijk,j->ijk',m,c))

shape of m =  (2, 3, 4)
Multiply each sub-matrix by either -1 or 100: 
 [[[   0   -1   -2   -3]
  [  -4   -5   -6   -7]
  [  -8   -9  -10  -11]]

 [[1200 1300 1400 1500]
  [1600 1700 1800 1900]
  [2000 2100 2200 2300]]]
Multiply rows of each sub-matrix by either 1, 100 or 10000: 
 [[[     0      1      2      3]
  [   400    500    600    700]
  [ 80000  90000 100000 110000]]

 [[    12     13     14     15]
  [  1600   1700   1800   1900]
  [200000 210000 220000 230000]]]
